config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "net_worth#index"
  get "net_worth/index"

  # AccountProviders
  resources :account_providers

  # Stocks
  resources :stocks do
    collection do
      get :preview
    end
    resources :stock_orders
  end

  # Deposits
  resources :deposits # do
  # resources :deposit_balances
  # end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
end

app/models/account_provider.rb
class AccountProvider < ApplicationRecord
    enum provider_type: { bank: 0, broker: 1, both: 2 }
    validates :name, presence: true
    validates :country, presence: true, inclusion: { in: ISO3166::Country.codes }
    has_many :stock_orders
    has_many :deposits
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :account_provider, optional: true
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :stock_orders, dependent: :destroy
end

app/models/stock_order.rb
class StockOrder < ApplicationRecord
  belongs_to :stock
  belongs_to :account_provider, optional: true
end

app/controllers/account_providers_controller.rb
class AccountProvidersController < ApplicationController
  def index
    @account_providers = AccountProvider.all
  end

  def show
    @account_provider = AccountProvider.find(params[:id])
  end

  def new
    @account_provider = AccountProvider.new
  end

  def create
    @account_provider = AccountProvider.new(account_provider_params)

    if @account_provider.save
      redirect_to @account_provider
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @account_provider = AccountProvider.find(params[:id])
  end

  def update
    @account_provider = AccountProvider.find(params[:id])

    if @account_provider.update(account_provider_params)
      redirect_to @account_provider
    else
      render :edit
    end
  end

  def destroy
    @account_provider = AccountProvider.find(params[:id])
    @account_provider.destroy

    redirect_to account_providers_path
  end

  private
    def account_provider_params
      params.require(:account_provider).permit(:name, :country, :provider_type)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  def index
    @deposits = Deposit.all
  end

  def show
    @deposit = Deposit.find(params[:id])
  end

  def new
    @deposit = Deposit.new
  end

  def create
    @deposit = Deposit.new(deposit_params)

    if @deposit.save
      redirect_to @deposit
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @deposit = Deposit.find(params[:id])
  end

  def update
    @deposit = Deposit.find(params[:id])

    if @deposit.update(deposit_params)
      redirect_to @deposit
    else
      render :edit
    end
  end

  def destroy
    @deposit = Deposit.find(params[:id])
    @deposit.destroy

    redirect_to deposits_path
  end

  private
    def deposit_params
      params.require(:deposit).permit(:name, :apr, :tax, :open_date, :maturity_date, :start_balance, :currency, :account_provider_id)
    end
end

app/controllers/net_worth_controller.rb
class NetWorthController < ApplicationController
  def index
  end
end

app/controllers/stock_orders_controller.rb
class StockOrdersController < ApplicationController
  def create
    @stock = Stock.find(params[:stock_id])
    @stock_order = @stock.stock_orders.create(stock_order_params)
    redirect_to stock_path(@stock)
  end

  def destroy
    @stock = Stock.find(params[:stock_id])
    @stock_order = @stock.stock_orders.find(params[:id])
    @stock_order.destroy
    redirect_to stock_path(@stock), status: :see_other
  end

  private
    def stock_order_params
      params.require(:stock_order).permit(:units, :unit_cost, :date, :account_provider_id)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @portfolio_data = StockService::Portfolio.history
  end

  def show
    @stock = Stock.find(params[:id])
    @stock_data = StockService::Stock.get_info(@stock)
  end

  def new
  end

  def create
    @stock = Stock.new(stock_params)

    if @stock.save
      redirect_to @stock
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @stock = Stock.find(params[:id])
  end

  def update
    @stock = Stock.find(params[:id])

    if @stock.update(stock_params)
      redirect_to @stock
    else
      render :edit
    end
  end

  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy

    redirect_to stocks_path
  end

  def preview
    symbol_data = StockService::Stock.preview(params[:symbol])
    redirect_to new_stock_path, alert: "Could not fetch stock data for the provided symbol." if symbol_data.empty?
    @stock = Stock.new(symbol: params[:symbol], alias: symbol_data[:name], currency: symbol_data[:currency])
  end

  private
    def stock_params
      params.require(:stock).permit(:symbol, :alias, :currency)
    end
end

app/helpers/account_providers_helper.rb
module AccountProvidersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deposit_helper.rb
module DepositHelper
  def self.maturity_date(deposit)
    deposit.maturity_date.strftime("%d/%m/%Y") # TODO: use I18n
  end

  def self.start_of_next_month
    Date.today.next_month.beginning_of_month.strftime("%d/%m/%Y") # TODO: use I18n
  end
  def self.duration(deposit)
    (deposit.maturity_date.year * 12 + deposit.maturity_date.month) - (deposit.open_date.year * 12 + deposit.open_date.month)
  end

  def self.tax(deposit, value)
    value * deposit.tax / 100
  end

  def self.value_increase(deposit, months)
    year_value_increase = deposit.start_balance * deposit.apr / 100
    year_value_increase * months / 12
  end

  def self.value_increase_with_maturity(deposit)
    duration_in_months = duration(deposit)
    value_increase(deposit, duration_in_months)
  end

  def self.value_at_maturity(deposit)
    value_increase = value_increase_with_maturity(deposit)
    tax = tax(deposit, value_increase)
    deposit.start_balance + value_increase - tax
  end

  def self.value_next_month(deposit)
    value_increase = value_increase(deposit, 1)
    tax = tax(deposit, value_increase)
    deposit.start_balance + value_increase - tax
  end

  def self.get_deposit_value(deposit)
    if deposit.maturity_date.present?
      value_increase = value_increase_with_maturity(deposit)
      {
        value: FormatService.format_currency(value_at_maturity(deposit), deposit.currency),
        tax: FormatService.format_currency(tax(deposit, value_increase), deposit.currency),
        value_increase: FormatService.format_currency(value_increase, deposit.currency),
        value_date: maturity_date(deposit)
      }
    else
      value_increase = value_increase(deposit, 1)
      {
        value: FormatService.format_currency(value_next_month(deposit), deposit.currency),
        tax: FormatService.format_currency(tax(deposit, value_increase), deposit.currency),
        value_increase: FormatService.format_currency(value_increase, deposit.currency),
        value_date: start_of_next_month
      }
    end
  end
end

app/helpers/net_worth_helper.rb
module NetWorthHelper
end

app/helpers/stock_orders_helper.rb
module StockOrdersHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/account_providers/_form.html.erb
<%= form_with model: account_provider do |form| %>
    <div>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
        <% account_provider.errors.full_messages_for(:name).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :country %><br>
        <%= form.select :country, ISO3166::Country.all.sort_by(&:iso_short_name).map { |country| [country.iso_short_name, country.alpha2] }, { prompt: 'Select a country' } %><br>
        <% account_provider.errors.full_messages_for(:country).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :provider_type %><br>
        <%= form.select :provider_type, AccountProvider.provider_types.keys.map { |key| [key.humanize, key] }, { prompt: 'Select Provider Type' } %><br>
        <% account_provider.errors.full_messages_for(:provider_type).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/account_providers/edit.html.erb
<h1>Edit Account Provider</h1>

<%= render "form", account_provider: @account_provider %>

app/views/account_providers/index.html.erb
<h1>Account Providers</h1>

<ul>
    <% @account_providers.each do |account_provider| %>
        <li>
            <%= link_to "#{ISO3166::Country[account_provider.country].emoji_flag} #{account_provider.name}", account_provider %>
        </li>
    <% end %>
</ul>


<%= link_to "New Account Provider", new_account_provider_path %>

app/views/account_providers/new.html.erb
<h1>New Account Provider</h1>

<%= render "form", account_provider: @account_provider %>

app/views/account_providers/show.html.erb
<h1><%= @account_provider.name %></h1>

<p>
    <%= ISO3166::Country[@account_provider.country].emoji_flag %> <%= ISO3166::Country[@account_provider.country].iso_short_name %><br>
    <%= @account_provider.provider_type.humanize %><br>
</p>

<ul>
    <li><%= link_to "Edit", edit_account_provider_path(@account_provider) %></li>
    <li><%= link_to "Destroy", account_provider_path(@account_provider), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
    } %></li>
</ul>

app/views/deposits/_form.html.erb
<%= form_with model: deposit do |form| %>
    <div>
        <%= form.label :name %>:
        <%= form.text_field :name %>
        <% deposit.errors.full_messages_for(:name).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :apr %>:
        <%= form.number_field :apr, step: '1e-2'  %> %
        <% deposit.errors.full_messages_for(:apr).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :tax %>:
        <%= form.number_field :tax, step: '1'  %> %
        <% deposit.errors.full_messages_for(:tax).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :start_balance %>:
        <%= form.number_field :start_balance, step: '1e-2'  %>
        <% deposit.errors.full_messages_for(:start_balance).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>


    <div>
        <%= form.label :currency %>:
        <%=
            form.select :currency,
            Money::Currency.all.sort_by(&:name).map { |currency| [currency.name, currency.iso_code] },
            { prompt: "Select Currency" }
        %><br>
        <% deposit.errors.full_messages_for(:currency).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :open_date %>:
        <%= form.date_field :open_date, min: '1988-01-01', max: Date.today %>
        <% deposit.errors.full_messages_for(:open_date).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :maturity_date %>:
        <%= form.date_field :maturity_date, min: Date.today %>
        <% deposit.errors.full_messages_for(:maturity_date).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :account_provider %>:
        <%= form.select :account_provider_id,
            AccountProvider.all.sort_by(&:name).map { |account_provider| [account_provider.name, account_provider.id] },
            { prompt: "Select Deposit Holder" }
        %>
        <% deposit.errors.full_messages_for(:account_provider_id).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/deposits/edit.html.erb
<h1>Edit Deposit</h1>

<%= render "form", deposit: @deposit %>

app/views/deposits/index.html.erb
<h1>Deposits</h1>


<% if !@deposits.empty? %>
    <% @deposits.each do |deposit| %>
        <% deposit_value = DepositHelper.get_deposit_value(deposit) %>
        <h2><%= deposit.name %></h2>

        Value at <%= deposit_value[:value_date] %>
        will be <%= deposit_value[:value] %>
        <span style="color: green;">+<%= deposit_value[:value_increase] %></span>
        (tax: <%= deposit_value[:tax] %>)

    <% end %>
<% end %>


<ul>
    <% @deposits.each do |deposit| %>
        <li>
            <%= link_to deposit.name, deposit %>
        </li>
    <% end %>
</ul>


<%= link_to "New Deposit", new_deposit_path %>

app/views/deposits/new.html.erb
<h1>New Deposit</h1>

<%= render "form", deposit: @deposit %>

app/views/deposits/show.html.erb
<h1><%= @deposit.name %></h1>

<p>
    <strong>APR:</strong>
    <%= @deposit.apr %> %
</p>

<p>
    <strong>TAX:</strong>
    <%= @deposit.tax %> %
</p>

<% if @deposit.open_date.present? %>
    <p>
        <strong>Open date:</strong>
        <%= @deposit.open_date %>
    </p>
<% end %>

<% if @deposit.maturity_date.present? %>
    <p>
        <strong>Maturity date:</strong>
        <%= @deposit.maturity_date %>
    </p>
<% end %>

<p>
    <strong>Start Balance:</strong>
    <%= Money.from_amount(@deposit.start_balance, @deposit.currency).format(format: FormatService.currency_format) %>
</p>
<%# TODO: add current balances %>

<% if @deposit.account_provider_id.present? %>
    <p>
        <strong>Account Holder:</strong>
        <%= @deposit.account_provider.name %>
    </p>
<% end %>

<ul>
    <li><%= link_to "Edit", edit_deposit_path(@deposit) %></li>
    <li><%= link_to "Destroy", deposit_path(@deposit), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
    } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Net Worth" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/net_worth/index.html.erb
<h1>Net Worth</h1>

<%= link_to "Stock Portfolio", stocks_path %><br>
<%= link_to "Deposits", deposits_path %><br>


<br><%= link_to "Account providers", account_providers_path %><br>

app/views/stock_orders/_form.html.erb
<%= form_with model: [ stock, stock.stock_orders.build ] do |form| %>
    <p>
        <%= form.label :units %>:
        <%= form.number_field :units, step: '1e-7' %>
    </p>
    <p>
        <%= form.label :unit_cost %>:
        <%= form.number_field :unit_cost, step: '1e-7'  %> (in <%= Money::Currency.new(stock.currency).symbol %>)
    </p>
    <p>
        <%= form.label :date %>:
        <%= form.date_field :date, min: '1988-01-01', max: Date.today %>
    </p>
    <p>
        <%= form.label :account_provider %>:
        <%= form.select :account_provider_id,
            AccountProvider.all.sort_by(&:name).map { |account_provider| [account_provider.name, account_provider.id] },
            { prompt: "Select Broker" }
        %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/stock_orders/_stock_order.html.erb
<p>
    <strong>Units:</strong>
    <%= stock_order.units %>
</p>

<p>
    <strong>Price per unit:</strong>
    <%= Money.from_amount(stock_order.unit_cost, stock_order.stock.currency).format %>
</p>

<p>
    <strong>Date:</strong>
    <%= stock_order.date %>
</p>

<% if stock_order.account_provider_id.present? %>
    <p>
        <strong>Broker:</strong>
        <%= stock_order.account_provider.name %>
    </p>
<% end %>

<p>
    <%= link_to "Delete Order", [stock_order.stock, stock_order], data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
    } %>
</p>

app/views/stocks/_form.html.erb
<%= form_with model: @stock do |form| %>
    <div>
        <%= form.label :symbol %><br>
        <%= form.text_field :symbol %>
        <% @stock.errors.full_messages_for(:symbol).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :alias %><br>
        <%= form.text_field :alias %>
        <% @stock.errors.full_messages_for(:alias).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :currency %><br>
        <%=
            form.select :currency,
            Money::Currency.all.sort_by(&:name).map { |currency| [currency.name, currency.iso_code] },
            { prompt: "Select Currency" }
        %><br>
        <% @stock.errors.full_messages_for(:currency).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
    <%= form.submit %>
    </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Edit Stock</h1>

<%= render "form", stock: @stock %>

app/views/stocks/index.html.erb
<h1>Portfolio</h1>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<%= javascript_include_tag 'portfolio_chart' %>
<script type="text/javascript">
    document.addEventListener('turbolinks:load', function() {
        google.charts.load('current', {'packages':['corechart']});
    });

    document.addEventListener('turbolinks:before-cache', function() {
        google.charts.unload();
    });

    google.charts.load('current', {'packages':['corechart']});

    <% for currency, data in @portfolio_data do %>
        <% if !data[:chart_data][:symbols].empty? %>
            console.log('<%= FormatService.grouping_symbol %>');
            google.charts.setOnLoadCallback(function() {
                drawChart(
                    <%= raw data[:chart_data].to_json %>,
                    '<%= currency.id %>',
                    '<%= FormatService.prefix(Money::Currency.new(currency.id).symbol) %>',
                    '<%= FormatService.grouping_symbol %>',
                    '<%= FormatService.decimal_symbol %>',
                    '<%= FormatService.suffix(Money::Currency.new(currency.id).symbol) %>',
                );
            });
        <% end %>
    <% end %>
</script>

<% for currency, data in @portfolio_data do %>

    <h2>Invested in <%= currency.name %></h2>

    <% if !data[:chart_data][:symbols].empty? %>
        <div id="chart_div_<%= currency.id %>" style="width: 100%; height: 500px; overflow: hidden;"></div>
    <% end %>

    Total Invested: <%= data[:total_invested_amount].format(format: FormatService.currency_format) %><br>
    Total Current Value: <%= data[:total_current_value].format(format: FormatService.currency_format) %>
    <% if data[:diff].amount > 0 %>
        <span style="color: green;">+<%= data[:diff].format(format: FormatService.currency_format)  %></span>
    <% else %>
        <span style="color: red;"><%= data[:diff].format(format: FormatService.currency_format)  %></span>
    <% end %>

    <ul>
        <% data[:stocks].each do |stock| %>
            <li>
                <%= link_to stock.alias, stock %>
            </li>
        <% end %>
    </ul>

<% end %>

<%= link_to "Add Stock", new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= form_with url: preview_stocks_path, method: :get, local: true do |form| %>
    <div class="field">
        <%= form.label :symbol, "Find Stock Symbol" %>
        <%= form.text_field :symbol %>
    </div>

    <%= form.submit "Load Stock Data" %>
<% end %>

app/views/stocks/preview.html.erb
<h1>Stock Preview</h1>

<%= render "form", stock: @stock %>

app/views/stocks/show.html.erb
<h1><%= @stock.alias %></h1>

<p>
    Symbol: <%= @stock.symbol %><br>
    Currency: <%= @stock.currency %><br>
    <% if @stock_data[:current_price].present? %>
        Current Price: <%= @stock_data[:current_price].format %><br>
        <% if @stock_data[:day_change].present? %>
            Day Change:
            <% if @stock_data[:day_change].amount > 0 %>
                <span style="color: green;">+<%= @stock_data[:day_change].format %></span>
            <% else %>
                <span style="color: red;"><%= @stock_data[:day_change].format %></span>
            <% end %><br>
        <% end %>
    <% end %>
    <% if @stock.stock_orders.present? %>
        Total Units: <%= @stock_data[:total_units] %><br>
        Total Invested Amount: <%= @stock_data[:total_invested_amount].format %><br>
        Average Unit Cost: <%= @stock_data[:average_unit_cost].format %><br>
        <% if @stock_data[:current_value].present? %>
            Current Value: <%= @stock_data[:current_value].format %><br>
        <% end %>
    <% end %>
</p>

<ul>
    <li><%= link_to "Edit", edit_stock_path(@stock) %></li>
    <li><%= link_to "Destroy", stock_path(@stock), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
    } %></li>
</ul>

<% if @stock.stock_orders.present? %>
    <h2>Orders:</h2>
    <%= render @stock.stock_orders %>
<% end %>

<h2>Add an order:</h2>
<%= render "stock_orders/form", stock: @stock %>